=== microsoft/devsquad-mlops/quickstart/schemas/cloud-setup/config.schema.1.0.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "pattern": "1.0.0"
    },
    "project": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 30,
          "pattern": "^\\S+$"
        },
        "alias": {
          "type": "string",
          "minLength": 1,
          "maxLength": 9,
          "pattern": "^\\S+$"
        },
        "location": {
          "type": "string",
          "enum": [
            "eastasia",
            "southeastasia",
            "centralus",
            "eastus",
            "eastus2",
            "westus",
            "northcentralus",
            "southcentralus",
            "northeurope",
            "westeurope",
            "japanwest",
            "japaneast",
            "brazilsouth",
            "australiaeast",
            "australiasoutheast",
            "southindia",
            "centralindia",
            "westindia",
            "jioindiawest",
            "canadacentral",
            "canadaeast",
            "uksouth",
            "ukwest",
            "westcentralus",
            "westus2",
            "koreacentral",
            "koreasouth",
            "francecentral",
            "francesouth",
            "australiacentral",
            "australiacentral2",
            "uaecentral",
            "uaenorth",
            "southafricanorth",
            "southafricawest",
            "switzerlandnorth",
            "switzerlandwest",
            "germanynorth",
            "germanywestcentral",
            "norwaywest",
            "norwayeast",
            "brazilsoutheast",
            "westus3"
          ]
        }
      },
      "required": [
        "alias",
        "location",
        "name"
      ]
    },
    "servicePrincipals": {
      "type": "array",
      "items": {      
          "type": "string",
          "minLength": 1,
          "maxLength": 260
        },
      "additionalProperties": false
    },
    "azureDevOps": {
      "type": "object",
      "properties": {
        "organization": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "project": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        }
      },
      "required": [
        "organization",
        "project"
      ]
    },
    "environments": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2,4}$": {
          "type": "object",
          "properties": {
            "subscriptionId": {
              "type": "string",
              "pattern": "^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$"
            },
            "servicePrincipalName": {
              "type": "string",
              "minLength": 1,
              "maxLength": 260
            },
            "serviceConnectionName": {
              "type": "string",
              "minLength": 1,
              "maxLength": 256
            }
          },
          "required": [
            "serviceConnectionName",
            "servicePrincipalName",
            "subscriptionId"
          ]
        }
      },
      "additionalProperties": false
    },
    "output": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "template": {
            "type": "string",
            "pattern": "[^/]+(?:\\.\\w+)?$"
          },
          "file": {
            "type": "string",
            "pattern": "[^/]+(?:\\.\\w+)?$"
          }
        },
        "required": [
          "file",
          "template"
        ]
      }
    }
  },
  "required": [
    "azureDevOps",
    "environments",
    "project",
    "servicePrincipals",
    "version"
  ]
}

=== microsoft/devsquad-mlops/quickstart/scripts/cloud-setup/configs/template.json
{
    "version": "1.0.0",
    "project": {
        "name": "<projectName>",
        "alias": "<projectAlias>",
        "location": "eastus"
    },
    "servicePrincipals": [
        "SP-<projectName>-DevTest"
    ],
    "azureDevOps": {
        "organization": "<orgName>",
        "project": "<projectName>"
    },
    "environments": {
        "dev": {
            "subscriptionId": "<subscriptionId>",
            "servicePrincipalName": "SP-<projectName>-DevTest",
            "serviceConnectionName": "spn-iac-dev"
        },
        "qa": {
            "subscriptionId": "<subscriptionId>",
            "servicePrincipalName": "SP-<projectName>-DevTest",
            "serviceConnectionName": "spn-iac-qa"
        },
        "prod": {
            "subscriptionId": "<subscriptionId>",
            "servicePrincipalName": "SP-<projectName>-DevTest",
            "serviceConnectionName": "spn-iac-prod"
        }
    },
    "output": [
        {
            "template": "quickstart/mlops/configs/template.json",
            "file": "quickstart/outputs/hol.json"            
        }
    ]
}

=== microsoft/devsquad-mlops/quickstart/scripts/cloud-setup/configs/hol.json
{
    "version": "1.0.0",
    "project": {
        "name": "hlops-hol",
        "alias": "hd578dd2",
        "location": "eastus"
    },
    "servicePrincipals": [
        "SP-hlops-hol-DevTest"
    ],
    "azureDevOps": {
        "organization": "gps-devsquad",
        "project": "hlops-hol"
    },
    "environments": {
        "dev": {
            "subscriptionId": "282236ee-0d0a-4acf-bf06-b0207a1e8b11",
            "servicePrincipalName": "SP-hlops-hol-DevTest",
            "serviceConnectionName": "spn-iac-dev"
        },
        "qa": {
            "subscriptionId": "282236ee-0d0a-4acf-bf06-b0207a1e8b11",
            "servicePrincipalName": "SP-hlops-hol-DevTest",
            "serviceConnectionName": "spn-iac-qa"
        },
        "prod": {
            "subscriptionId": "282236ee-0d0a-4acf-bf06-b0207a1e8b11",
            "servicePrincipalName": "SP-hlops-hol-DevTest",
            "serviceConnectionName": "spn-iac-prod"
        }
    },
    "output": [
        {
            "template": "quickstart/configs/dataops/template.json",
            "file": "quickstart/outputs/hol.json"            
        }
    ]
}
